#!/usr/bin/env python3
# v37: generates the device-local packages/cytech_email.yaml (the two smtp
# notify platforms as LITERAL values from /config/.cytech_secrets -- the
# credentials never live in the repo and nothing references !secret). This
# file is the single source of truth for the generator: ensure_email_secrets()
# in first_boot.sh and cytech_register_email.sh both call it. Byte-compares
# the file it writes so unchanged content doesn't restart HA needlessly.
# Prints exactly one status line; callers grep for "written"/"removed" to
# decide whether a core restart is needed.
import os
import yaml

CFG = '/config/.cytech_secrets'
PKG = '/config/packages/cytech_email.yaml'

VALUES = {}
if os.path.exists(CFG):
    with open(CFG) as f:
        for line in f:
            line = line.strip()
            if line and '=' in line and not line.startswith('#'):
                k, v = line.split('=', 1)
                VALUES[k.strip()] = v.strip()

PASS = VALUES.get('CY_SMTP_PASS')
if not PASS:
    if os.path.exists(PKG):
        os.remove(PKG)
        print("no CY_SMTP_PASS -- removed stale packages/cytech_email.yaml")
    else:
        print("CY_SMTP_PASS not in .cytech_secrets -- email alerts disabled")
    raise SystemExit(0)

data = {
    'notify': [
        {
            'platform': 'smtp', 'name': 'cytech_alert_support',
            'server': 'mail.server282.com', 'port': 465, 'encryption': 'tls',
            'username': VALUES.get('CY_SMTP_USER', ''),
            'password': PASS,
            'sender': 'ucmapi@cytech.biz', 'recipient': 'support@cytech.biz',
        },
        {
            'platform': 'smtp', 'name': 'cytech_alert_email',
            'server': 'mail.server282.com', 'port': 465, 'encryption': 'tls',
            'username': VALUES.get('CY_SMTP_USER', ''),
            'password': PASS,
            'sender': 'ucmapi@cytech.biz',
            'recipient': VALUES.get('CY_SMTP_RECIPIENT', ''),
        },
    ],
}
text = ('# generated by ensure_email_secrets -- device-local, never in repo\n'
        + yaml.safe_dump(data, default_flow_style=False, sort_keys=False))
old = open(PKG).read() if os.path.exists(PKG) else None
if old == text:
    print("email package already up to date -- no change")
    raise SystemExit(0)
with open(PKG, 'w') as f:
    f.write(text)
os.chmod(PKG, 0o600)
print("package packages/cytech_email.yaml written")
